### PR TITLE
changed uint to int

### PR DESCRIPTION
**Pull request by brucelane**
other quick and dirty fixes to make it work with visual studio 2015

### CODE REVIEW

**Comment by frauzufall** [comment]
Thanks! Could you rename the old "uint" appearances to "unsigned int" to reduce warnings?

**Comment by brucelane** [comment]
done

**Comment by frauzufall** [comment]
Thank you!

**Comment by brucelane** [comment]
you're welcome!
I plan to use it for my Videodrömm project!

**Pull request merged**
